In [1]:
import numpy as np

In [2]:
data1 = [[1,2,3,4],[5,6,7,8]]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr1.ndim

2

In [6]:
arr1.shape

(2, 4)

In [7]:
arr1.dtype

dtype('int32')

In [8]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
arr2 = np.arange(10)

In [11]:
reshape_array=np.arange(25).reshape(5,5)

In [13]:
reshape_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
reshape_array[:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
reshape_array[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
reshape_array.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [17]:
a = [4,7,9]
b = [3,7,9]

np.add(a,b)

array([ 7, 14, 18])